In [4]:
import pickle
import pandas as pd
import numpy as np

In [7]:
data = []
# with open(f'myGCN/hidden_features_0','rb') as f:
with open(f'myGraphSAGE/hidden_features_10','rb') as f:
    data = pickle.load(f)

In [9]:
print(f'stacked hidden features{len(data)}')

for layer in range(len(data)):
    print(f'total number of obstacles in layer {layer} : {data[layer].size()}')

for layer in range(len(data)):
    print(data[layer])

stacked hidden features4
total number of obstacles in layer 0 : torch.Size([800, 1199])
total number of obstacles in layer 1 : torch.Size([800, 8])
total number of obstacles in layer 2 : torch.Size([800, 8])
total number of obstacles in layer 3 : torch.Size([800, 1])
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.6495, 0.9144, 0.8877],
        [0.0000, 0.0000, 0.0000,  ..., 0.6495, 0.9144, 0.8877],
        [0.0000, 0.0000, 0.0000,  ..., 0.6495, 0.9144, 0.8877],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.5025, 0.9930, 0.8247],
        [0.0000, 0.0000, 0.0000,  ..., 0.5025, 0.9930, 0.8247],
        [0.0000, 0.0000, 0.0000,  ..., 0.5025, 0.9930, 0.8247]],
       device='cuda:0')
tensor([[ 5.9820,  1.7180, -0.9773,  ...,  5.7105, -0.8176, -0.8857],
        [-0.9819,  4.5643, -0.9835,  ...,  5.5419,  2.0575, -0.8896],
        [ 1.2347,  1.8849, -0.8161,  ...,  4.0878, -0.7363, -0.8356],
        ...,
        [ 0.5952,  3.7322, -0.0963,  ...,  4.0499, -0.0441, -0.8709],
        [-0.9908,

In [10]:
print(data[0][0].tolist().count(1))
print(data[0][1].tolist().count(1))
print(data[0][2].tolist().count(1))
print((data[0][0]-data[0][1]).tolist().count(-1))

25
34
30
34


In [11]:
print(data[0][0].tolist().count(1))
print(data[0][0].tolist().count(0))

25
1170


In [12]:
data[0][0]

tensor([0.0000, 0.0000, 0.0000,  ..., 0.6495, 0.9144, 0.8877], device='cuda:0')