In [8]:
import pickle
import pandas as pd
import numpy as np

In [9]:
data = []
with open(f'hidden_features_0','rb') as f:
    data = pickle.load(f)

In [10]:
for i in range(len(data)):
    for j in range(20,25):
        print(data[i][j][:15])

tensor([ 0.0280,  0.0358, -0.1110, -0.0480, -0.0149,  0.0996,  0.0386,  0.0062,
         0.0326, -0.0033,  0.0091, -0.0268,  0.0475, -0.0402,  0.0369],
       device='cuda:0', grad_fn=<SliceBackward>)
tensor([ 0.0464,  0.0646, -0.0600, -0.0292, -0.0653,  0.0563,  0.0561,  0.0276,
         0.0162,  0.0082, -0.0276, -0.0387, -0.0037,  0.0108,  0.0067],
       device='cuda:0', grad_fn=<SliceBackward>)
tensor([ 0.0444,  0.0945, -0.0846, -0.0224, -0.0387,  0.0850, -0.0060,  0.0861,
        -0.0286, -0.0680,  0.0274, -0.0590,  0.0701, -0.0152, -0.0155],
       device='cuda:0', grad_fn=<SliceBackward>)
tensor([ 0.0450,  0.0532, -0.0984, -0.0312, -0.0323,  0.0861, -0.0308,  0.0037,
        -0.0111, -0.0007, -0.0207, -0.0642,  0.0097,  0.0218,  0.0200],
       device='cuda:0', grad_fn=<SliceBackward>)
tensor([ 0.0109,  0.0308, -0.0937,  0.0122, -0.0008,  0.0775, -0.0068,  0.0247,
         0.0628, -0.0260, -0.0390, -0.0119, -0.0009, -0.0179,  0.0369],
       device='cuda:0', grad_fn=<SliceBackwa

In [7]:
for j in range(0,25):
    print(data[-1][j][:15].item())

0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
0.4889676570892334
