In [27]:
import pickle
import pandas as pd
import numpy as np

In [28]:
data = []
# with open(f'myGCN/hidden_features_0','rb') as f:
with open(f'myGraphSAGE/hidden_features_1','rb') as f:
    data = pickle.load(f)

In [29]:
print(f'stacked hidden features{len(data)}')

for layer in range(len(data)):
    print(f'total number of obstacles in layer {layer} : {data[layer].size()}')

for layer in range(len(data)):
    print(data[layer])

stacked hidden features5
total number of obstacles in layer 0 : torch.Size([12, 68])
total number of obstacles in layer 1 : torch.Size([12, 32])
total number of obstacles in layer 2 : torch.Size([12, 32])
total number of obstacles in layer 3 : torch.Size([12, 1])
total number of obstacles in layer 4 : torch.Size([12, 1])
tensor([[ 1.6658e+01,  2.9676e+01,  9.3602e-02,  4.1089e-01, -4.9242e+00,
          9.4371e+00,  1.5232e+01,  4.8913e+01, -4.1955e+00,  2.8489e+01,
          5.1663e+00, -1.9810e+00, -2.3651e-02, -3.5257e+00,  2.4098e+01,
         -3.6231e+01,  8.2339e+00, -2.1467e+01, -1.1226e+01, -4.5804e+00,
         -1.2464e+02,  1.4317e+00,  1.2551e+01, -1.3178e+01,  3.8053e+00,
         -8.5698e-01, -4.6997e+01,  8.3507e+00, -5.7756e+01, -1.5302e+01,
         -3.0723e+00, -5.0217e+00, -6.9342e+00, -6.6021e+01,  1.0039e+01,
         -5.6097e+01,  9.0217e+00,  1.6016e+01, -2.4594e+00, -1.6061e+01,
         -8.8018e+00,  1.0695e+01, -8.0547e+00, -1.5448e+00, -3.2936e+00,
         -3

In [30]:
print(data[0][0].tolist().count(1))
print(data[0][1].tolist().count(1))
print(data[0][2].tolist().count(1))
print((data[0][0]-data[0][1]).tolist().count(-1))

0
0
0
0


In [31]:
print(data[0][0].tolist().count(1))
print(data[0][0].tolist().count(0))

0
0


In [32]:
data[0][0]

tensor([ 1.6658e+01,  2.9676e+01,  9.3602e-02,  4.1089e-01, -4.9242e+00,
         9.4371e+00,  1.5232e+01,  4.8913e+01, -4.1955e+00,  2.8489e+01,
         5.1663e+00, -1.9810e+00, -2.3651e-02, -3.5257e+00,  2.4098e+01,
        -3.6231e+01,  8.2339e+00, -2.1467e+01, -1.1226e+01, -4.5804e+00,
        -1.2464e+02,  1.4317e+00,  1.2551e+01, -1.3178e+01,  3.8053e+00,
        -8.5698e-01, -4.6997e+01,  8.3507e+00, -5.7756e+01, -1.5302e+01,
        -3.0723e+00, -5.0217e+00, -6.9342e+00, -6.6021e+01,  1.0039e+01,
        -5.6097e+01,  9.0217e+00,  1.6016e+01, -2.4594e+00, -1.6061e+01,
        -8.8018e+00,  1.0695e+01, -8.0547e+00, -1.5448e+00, -3.2936e+00,
        -3.4507e+00,  1.4691e+02, -9.0156e+00, -2.3443e+01,  2.4251e+01,
         4.0009e+01, -1.4993e+01,  5.4830e+00,  1.0219e+00, -2.9751e+01,
         1.2281e+01, -7.2298e-01,  5.7223e+01, -5.2843e+01,  1.1798e+01,
        -3.4287e+00,  2.1703e+01,  9.4687e+00, -1.8863e+01,  6.4270e-02,
         4.5532e-02,  8.4180e-01,  9.5117e-01], dev

In [33]:
data[0]

tensor([[ 1.6658e+01,  2.9676e+01,  9.3602e-02,  4.1089e-01, -4.9242e+00,
          9.4371e+00,  1.5232e+01,  4.8913e+01, -4.1955e+00,  2.8489e+01,
          5.1663e+00, -1.9810e+00, -2.3651e-02, -3.5257e+00,  2.4098e+01,
         -3.6231e+01,  8.2339e+00, -2.1467e+01, -1.1226e+01, -4.5804e+00,
         -1.2464e+02,  1.4317e+00,  1.2551e+01, -1.3178e+01,  3.8053e+00,
         -8.5698e-01, -4.6997e+01,  8.3507e+00, -5.7756e+01, -1.5302e+01,
         -3.0723e+00, -5.0217e+00, -6.9342e+00, -6.6021e+01,  1.0039e+01,
         -5.6097e+01,  9.0217e+00,  1.6016e+01, -2.4594e+00, -1.6061e+01,
         -8.8018e+00,  1.0695e+01, -8.0547e+00, -1.5448e+00, -3.2936e+00,
         -3.4507e+00,  1.4691e+02, -9.0156e+00, -2.3443e+01,  2.4251e+01,
          4.0009e+01, -1.4993e+01,  5.4830e+00,  1.0219e+00, -2.9751e+01,
          1.2281e+01, -7.2298e-01,  5.7223e+01, -5.2843e+01,  1.1798e+01,
         -3.4287e+00,  2.1703e+01,  9.4687e+00, -1.8863e+01,  6.4270e-02,
          4.5532e-02,  8.4180e-01,  9.